theme = "catppuccin_mocha"

[editor]
line-number = "relative"
true-color = true
color-modes = true
cursorline = true
rulers = [80, 120]

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[keys.normal]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.normal.space.w]
v = ["vsplit", "file_picker"]
h = ["hsplit", "file_picker"]
