theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
true-color = true
color-modes = true
cursorline = true
rulers = [80, 120]

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[keys.normal.space.w]
h = "hsplit"
