[[language]]
auto-format = true
name = "bash"

[language.formatter]
args = ["-s"]
command = "shfmt"

[[language]]
auto-format = true
name = "markdown"

[language.formatter]
args = ["--parser", "markdown"]
command = "prettier"

[[language]]
auto-format = true
name = "nix"

[language.formatter]
command = "nixpkgs-fmt"

[[language]]
auto-format = true
name = "rust"

[[language]]
auto-format = true
name = "dockerfile"

[[language]]
auto-format = true
name = "yaml"

[language.formatter]
args = ["--parser", "yaml"]
command = "prettier"

[[language]]
auto-format = true
language-servers = [{except-features = ["format"], name = "vscode-json-language-server"}, "biome-lsp"]
name = "json"

[language.formatter]
args = ["format", "--stdin-file-path", "a.json"]
command = "biome"

[[language]]
auto-format = true
language-servers = ["python-lsp"]
name = "python"

[language.formatter]
args = ["--quiet", "-"]
command = "black"

[[language]]
auto-format = true
name = "r"

[[language]]
auto-format = true
language-servers = ["emmet-lsp", "vscode-html-language-server"]
name = "html"

[language.formatter]
args = ["--parser", "html"]
command = "prettier"

[[language]]
auto-format = true
language-servers = ["vscode-css-language-server"]
name = "css"

[language.formatter]
args = ["--parser", "css"]
command = "prettier"

[[language]]
auto-format = true
language-servers = ["vscode-css-language-server"]
name = "scss"

[language.formatter]
args = ["--parser", "scss"]
command = "prettier"

[[language]]
auto-format = true
language-servers = [{except-features = ["format"], name = "typescript-language-server"}, "biome-lsp"]
name = "javascript"

[language.formatter]
args = ["format", "--stdin-file-path", "a.ts"]
command = "biome"

[[language]]
auto-format = true
language-servers = [{except-features = ["format"], name = "typescript-language-server"}, "biome-lsp"]
name = "typescript"

[language.formatter]
args = ["format", "--stdin-file-path", "a.ts"]
command = "biome"

[[language]]
auto-format = true
language-servers = [{except-features = ["format"], name = "typescript-language-server"}, "biome-lsp"]
name = "tsx"

[language.formatter]
args = ["format", "--stdin-file-path", "a.tsx"]
command = "biome"

[[language]]
auto-format = true
language-servers = ["svelteserver", "tailwind-lsp"]
name = "svelte"

[language.formatter]
args = ["--parser", "svelte"]
command = "prettier"

[[language]]
auto-format = true
language-servers = ["astro-lsp", "tailwind-lsp"]
name = "astro"

[language.formatter]
args = ["--parser", "astro"]
command = "prettier"

[[language]]
auto-format = true
name = "prisma"

[language-server]
[language-server.astro-lsp]
args = ["--stdio"]
command = "astro-ls"

[language-server.astro-lsp.config.typescript]
tsdk = "/nix/store/5vp84z1qx1nv65vq99xgj9my9psqg5zm-typescript-5.4.5/lib/node_modules/typescript/lib/"

[language-server.biome-lsp]
args = ["lsp-proxy"]
command = "biome"

[language-server.emmet-lsp]
args = ["--stdio"]
command = "emmet-ls"

[language-server.python-lsp]
args = ["--stdio"]
command = "pyright-langserver"

[language-server.python-lsp.config]

[language-server.tailwind-lsp]
args = ["--stdio"]
command = "tailwindcss-language-server"
