window:
  dimensions:
    columns: 100
    lines: 25

  padding:
    x: 4
    y: 4

font:
  size: 12.0
  
  offset:
    y: 2
  
  normal:
    family: Cascadia Code PL
    style: Regular
   
  italic:
    family: Cascadia Code PL
    style: Italic
  
  bold:
    family: Cascadia Code PL
    style: Bold
 
cursor:
  style:
    shape: Beam
    blinking: On

selection:
  save_to_clipboard: true

# gruvbox material
colors:
  primary:
    background: '0x282828'
    foreground: '0xdfbf8e'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'
 
