window:
  dimensions:
    columns: 100
    lines: 25

  padding:
    x: 4
    y: 4

font:
  size: 12.0
  
  offset:
    y: 2
  
  normal:
    family: Cascadia Code PL
    style: Regular
   
  italic:
    family: Cascadia Code PL
    style: Italic
  
  bold:
    family: Cascadia Code PL
    style: Bold
 
cursor:
  style:
    shape: Beam
    blinking: On

selection:
  save_to_clipboard: true

# mayukai dark
colors:
  primary:
    background: '0x1b1c24'
    foreground: '0xcbccc6'

  normal:
    black: '0x191e2a'
    red: '0xed8274'
    green: '0xa6cc70'
    yellow: '0xfad07b'
    blue: '0x95e6cb'
    magenta: '0xcfbafa'
    cyan: '0x95e6cb'
    white: '0xc7c7c7'

  bright:
    black: '0x686868'
    red: '0xf28779'
    green: '0xbae67e'
    yellow: '0xffd580'
    blue: '0x95e6cb'
    magenta: '0xd4bfff'
    cyan: '0x95e6cb'
    white: '0xffffff'