theme = "rose_pine_moon"
[editor]
color-modes = true
cursorline = true
line-number = "relative"
rulers = [80, 120]
scrolloff = 15
true-color = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[keys]
[keys.insert]
down = ["no_op"]
left = ["no_op"]
right = ["no_op"]
up = ["no_op"]

[keys.normal]
A-h = ["unindent"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-l = ["indent"]
A-x = ["extend_to_line_bounds"]
X = ["extend_line_up", "extend_to_line_bounds"]
down = ["no_op"]
left = ["no_op"]
right = ["no_op"]
up = ["no_op"]

[keys.normal.space.w]
"=" = ["vsplit"]
minus = ["hsplit"]

[keys.select]
A-x = ["extend_to_line_bounds"]
X = ["extend_line_up", "extend_to_line_bounds"]
down = ["no_op"]
left = ["no_op"]
right = ["no_op"]
up = ["no_op"]
