[scripts.color]
alias = 'color'
command = 'c=$@ && echo -n "\e[48;2;$(printf "%d;%d;%d" 0x${c:0:2} 0x${c:2:2} 0x${c:4:2})m\e[1m" && echo -n " #$c " && echo "\e[0m"'

[scripts.eslint]
alias = 'eslint'
command = 'eslint --fix $@'

[scripts.kill]
alias = 'kill'
command = 'ps aux | grep -i -m 1 $@ | awk "{print $2}" | xargs kill'

[scripts.c]
alias = 'c'
command = 'gcc $@ && ./a.out && rm ./a.out'

[default]
