[scripts.ip]
alias = 'ip'
command = 'nmcli c m "Wired connection 1" ipv4.method manual ipv4.addr "$@/24" ipv4.gateway "$(echo $@ | grep -o "^\w*.\w*.\w*").1" ipv4.dns 8.8.8.8'

[scripts.color]
alias = 'color'
command = 'c=$@ && echo -n "\e[48;2;$(printf "%d;%d;%d" 0x${c:0:2} 0x${c:2:2} 0x${c:4:2})m\e[1m" && echo -n " #$c " && echo "\e[0m"'

[scripts.crow]
alias = 'crow'
command = 'crow -w $@ ./$@'

[scripts.c]
alias = 'c'
command = 'gcc $@ && ./a.out && rm ./a.out'

[default]
