#!/usr/bin/env bash

git stash
git checkout deploy

mkdir ~/.dotfiles/alacritty -p
mkdir ~/.dotfiles/tmux -p
mkdir ~/.dotfiles/fish -p
cp ~/.config/alacritty/alacritty.toml ~/.dotfiles/alacritty/config.toml -f
cp ~/.config/tmux/tmux.conf ~/.dotfiles/tmux/tmux.conf -f
cp ~/.config/fish/config.fish ~/.dotfiles/fish/config.fish -f

mkdir ~/.dotfiles/starship -p
cp ~/.config/starship.toml ~/.dotfiles/starship/config.toml -f

mkdir ~/.dotfiles/gh -p
mkdir ~/.dotfiles/git -p
cp ~/.config/gh/config.yml ~/.dotfiles/gh/config.yml -f
cp ~/.config/git/config ~/.dotfiles/git/config -f

mkdir ~/.dotfiles/helix -p
cp ~/.config/helix/config.toml ~/.dotfiles/helix/config.toml -f
cp ~/.config/helix/languages.toml ~/.dotfiles/helix/languages.toml -f

ls -R >index.html

git add .
git cs "deploy: deploy dotfiles ($(date))"
git push -u origin deploy
