# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/hf2jws9gbi7cynkh1mbyhy21ad2f63cg-hm-session-vars.fish

set fish_greeting
fish_config theme choose "Rosé Pine Moon"
zoxide init fish | source


status is-login; and begin

    # Login shell initialisation


end

status is-interactive; and begin

    # Abbreviations


    # Aliases
    alias cat bat
    alias cd z
    alias cp xcp
    alias diff delta
    alias du dust
    alias eza_ 'eza --icons -s type --git'
    alias find fd
    alias grep rg
    alias l 'eza_ -l --git-ignore'
    alias la 'eza_ -la'
    alias ls 'eza_ --git-ignore'
    alias lsa 'eza_ --git-ignore'
    alias lt 'eza_ -T --git-ignore'
    alias lta 'eza_ -Ta --git-ignore -I .git'
    alias ps procs
    alias rm rip
    alias sed sd
    alias top btop

    # Interactive shell initialisation
    if test "$TERM" != dumb
        eval (/home/dreisss/.nix-profile/bin/starship init fish)

    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/dreisss/.local/share/fish/home-manager_generated_completions" $post
    end

    /nix/store/s6w85517i1a8habjim1725jmk7vdqxmi-direnv-2.34.0/bin/direnv hook fish | source


end
